# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Digital Manuscripts in the Classroom
name: Leiden University Libraries
email: cds@library.leidenuniv.nl
description: >- # this means to ignore newlines until "baseurl:"
  We offer digital manuscripts for your classroom.
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://digmanclass.universiteitleiden.nl" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ubleiden
github_username:  LeidenUniversityLibrary

collections:
  routes:
    output: true
    permalink: /:collection/:path/
  manuscripts:
    output: true
    permalink: /:collection/:path/
    sort_by: route
  quill:
    output: false
  glossary:
    output: false

defaults:
  - scope:
      path: ""
    values:
      sidebar:
        nav: dmc
  - scope:
      path: ""
      type: "manuscripts"
    values:
      layout: manuscript

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  # - jekyll-feed
  - jekyll-scholar
  - jekyll-target-blank

atom_feed:
  hide: true
social:
  type: Organization
logo: "/assets/img/UBL.png"
footer_scripts: []

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - mirador/
